### ISSUE TITLE
pre-rotated & half-width

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFonts#10]
いつも開発ありがとうございます。相談に伺いました。
原ノ味フォントの縦組み用に、半角幅字形のpre-rotatedのサポートをお願いできないでしょうか。

japanese-otf{-uptex} の方で \CIDx{} の多書体化を検討していますが、原ノ味フォントではCJKのいずれも該当のCIDにグリフの割り当てがないようで、テストをすると豆腐になってしまっています。
[\CIDC{}, \CIDT{}, \CIDK{}の多書体化](https://github.com/texjporg/japanese-otf-mirror/issues/25#top)
テストは [こちら](https://github.com/texjporg/japanese-otf-mirror/commit/9e2a2b21b0f12e040b5d3b65aca42758f8be46ca)

横組み用の普通の半角幅のグリフがある場合、回転して全角幅にすれば作れるグリフが(全てではないですが)かなり作れるように思います。ASCII文字の半角幅、半角カタカナなどは出来そうです。
japanese-otfでは使えませんがProportionalのpre-rotatedも作れるかもしれません。

需要は少ないと思うので、是非にというほどではないのですが、一度ご検討いただけるとありがたいです。

**Comment by trueroad** [comment]
ありがとうございます。
仰る通り90度回転と平行移動は実績があるのでグリフを作ることはできそう、
横幅の調整も実績ありますのでできそうに思います。

ただ、半角幅やプロポーショナル幅のグリフを90度回転させると、
恐らく高さ深さなどの調整が必要になってしまうのではないかと思います。
これまですべてのグリフの高さ深さはまったく同じで調整もしていなかった
（90度回転したグリフは全角幅でボディが正方形だったため変更不要だった）
ため、そこをどうすればいいのか考える必要がありそうです。

実際のAJ1フォントではどのようになっているのかも気になる所です。

対応していないのは需要が少なそうだというのもありますが、
この手のグリフに対応したソフトウェアも少なそうで、
どうやって使えばいいか動作テストにも困りそうだったためでもあります。

japanese-otf が今後対応するということであれば考えてみたいと思います。

**Comment by t-tk** [comment]
ご検討ありがとうございます。
japanese-otf(-uptex) で対応済みまたは対応検討中のCIDのリストは
https://github.com/texjporg/japanese-otf-mirror/issues/25#issuecomment-1562775213
に記載しました。

斎藤さんオリジナルのotfパッケージでも CID+8950..9353 あたりは縦組み時に正しく組めるよう作りこまれているようです。
今回は、さらに拡張(AJのCID対応の拡張とGB,CNS,Koreaの半角対応)を試みています。

pre-rotated & half-widthは、以下のようになっているように見えます。
縦組み時は、グリフ自体は全角の正方形のボディを持っていて、上半分にグリフがあり、下半分が空白になっている。
全角幅を1.0として、フォント自体は「高さ0.5, 深さ0.5, 文字送り1.0幅」で、文字ごとにvfで-0.5zw だけ位置を戻して文字送りが半角相当になるようにする。
pre-rotated & half-widthのグリフの横組み時は、普通の全角グリフと同様の高さ、深さ、文字送り。

**Comment by trueroad** [comment]
> pre-rotated & half-widthは、以下のようになっているように見えます。 縦組み時は、グリフ自体は全角の正方形のボディを持っていて、上半分にグリフがあり、下半分が空白になっている。 全角幅を1.0として、フォント自体は「高さ0.5, 深さ0.5, 文字送り1.0幅」で、文字ごとにvfで-0.5zw だけ位置を戻して文字送りが半角相当になるようにする。 pre-rotated & half-widthのグリフの横組み時は、普通の全角グリフと同様の高さ、深さ、文字送り。

こちらは jfm の設定をそのようにしているという理解でよいでしょうか。
Adobe-Japan1 の OpenType/CFF フォントとして IBMPlexSansJP-Regular.otf の中身を見ているのですが違っているようでしたので。

私の理解と IBMPlexSansJP-Regular.otf の中身を調査したところを記載しておきます。

* ascender （高さ）
    + フォント内の全グリフで共通の設定
    + `OS/2` テーブルの `sTypoAscender` 設定値
    + OpenType/CFF の場合、通常は 880 固定
    + IBMPlexSansJP-Regular.otf でも 880
* decender （深さ）
    + フォント内の全グリフで共通の設定
    + `OS/2` テーブルの `sTypoDescender` 設定値
    + OpenType/CFF の場合、通常は -120 固定
    + IBMPlexSansJP-Regular.otf でも -120
* height （高さ？）
    + グリフ毎の個別の設定
    + `vmtx` テーブルで CID 毎に設定
    + OpenType/CFF の場合、通常は 1000
    + IBMPlexSansJP-Regular.otf ではほとんどのグリフは 1000 だが、半角の回転形だと 500 、プロポーショナルの回転形だとグリフ毎に値が異なる
        - プロポーショナルの場合、回転前グリフの `hmtx` テーブルに設定されている width と回転後グリフの `vmtx` テーブルに設定されている height が一致する組み合わせと一致しない組み合わせの両パターンある（法則不明）
* vorigin （縦組み時の y 軸原点座標）
    + デフォルト値設定とグリフ毎の個別設定
    + `VORG` テーブルの設定
    + 通常はデフォルト 880 として、880 ではないグリフのみ個別設定される
    + IBMPlexSansJP-Regular.otf でもデフォルト 880 、個別設定のグリフはほとんどなくて回転形には個別設定されていない（つまりデフォルトの 880 が適用される）

IBMPlexSansJP-Regular.otf が標準的な Adobe-Japan1 フォントかというと疑問ではあり、この辺が小塚やヒラギノなどでどうなっているのかが気になっています。

**Comment by trueroad** [comment]
回転形のグリフがどの位置（座標）に置かれているのかについても簡単に調べてみました。
すべてのグリフを確認したわけではありませんが、一応、回転前グリフを全角幅だとみなして 90 度右回転した位置に置いてある、ような感じに見えます。
例によって IBMPlexSansJP-Regular.otf の場合ですので、小塚やヒラギノでどうなっているのかが気になっています。

以下の画像は下記の内容のファイル test.tbl を用意し、

```test.tbl
# name dummy
cid00002        1000
cid00232        1000
cid08721        1000
cid08951        1000
```

ttx と [calc_letter_face.py](https://github.com/trueroad/HaranoAjiFonts-generator/blob/b5481e33400c5106a2785ff2c3bde5257c77e793/script/calc_letter_face.py) を使って、以下のようにすると表示できます（python-tkinter などが必要です）。

```
$ ttx -s IBMPlexSansJP-Regular.otf
$ ./calc_letter_face.py --debug test.tbl IBMPlexSansJP-Regular.C_F_F_.ttx
```

グリフが描画されたウィンドウが 1 つ出ますので、それを閉じると次のグリフのウィンドウが表示され、4 回表示・閉じるを繰り返すと終了します。
白線が全角の場合のボディとベースラインを示しています。
ボディの左下座標が (0, -120) 右上座標が (1000, 880) で、ベースラインは (0, 0) - (1000, 0) の直線です。
緑破線がレターフェイスを示しています。

CID+2：プロポーショナルの !
![glyph_cid00002](https://github.com/trueroad/HaranoAjiFonts/assets/3464255/75cd19b3-3d8d-4137-9a5b-bb21965992f0)

CID+8721：CID+2 の回転形
![glyph_cid08721](https://github.com/trueroad/HaranoAjiFonts/assets/3464255/2626bf7c-658a-4522-ad7c-b4ea1bd69606)

CID+232：半角の !
![glyph_cid00232](https://github.com/trueroad/HaranoAjiFonts/assets/3464255/aafc0916-8fd7-4236-aa21-48e285b12bea)

CID+8951：CID+232 の回転形
![glyph_cid08951](https://github.com/trueroad/HaranoAjiFonts/assets/3464255/c060869b-8381-4bed-bcea-b6be9db8636e)

**Comment by t-tk** [comment]
とりあえずすぐわかる部分だけ回答です。

> こちらは jfm の設定をそのようにしているという理解でよいでしょうか。

縦組みのjfmは、高さ0.5、深さ0.5、文字幅0.5zw になっていて、
文字幅1.0zwとして「文字ごとに-0.5zw だけ位置を戻す」がvfの設定にあると思います。

jfm を生成するplは、サブフォント毎にありますが一例は↓です。
https://github.com/texjporg/japanese-otf-mirror/blob/7a7c3cc0e600f5d1a2716832c661255fc1a38dbc/japanese-otf/basepl/base2-v.pl#LL27-L31

vfの部分は、↓のコードから生成されています。
https://github.com/texjporg/japanese-otf-mirror/blob/7a7c3cc0e600f5d1a2716832c661255fc1a38dbc/japanese-otf/script/mkcidvf.pl#LL72-L80

横組みの場合の CID+8951 は、japanese-otf (otfbeta) では、デフォルトの全角横組みのまま(高さ0.88, 深さ0.12, 文字幅1.0、vfによる移動無し)です。意図してその値にしたのか、未対応のつもりだがデフォルト値が入っているだけなのか、は不明です。
https://github.com/texjporg/japanese-otf-mirror/blob/7a7c3cc0e600f5d1a2716832c661255fc1a38dbc/japanese-otf/basepl/base2-h.pl#LL27-L31

**Comment by t-tk** [comment]
> すべてのグリフを確認したわけではありませんが、一応、回転前グリフを全角幅だとみなして 90 度右回転した位置に置いてある、ような感じに見えます。

そうですね。
Adobe の 5078.Adobe-Japan1-6.pdf を見てもグリフの配置はそのように見えます。

**Comment by t-tk** [comment]
IBM Plex v6.3.0 の IBMPlexSansJP-Regular.otf で上記[テスト](https://github.com/texjporg/japanese-otf-mirror/commit/9e2a2b21b0f12e040b5d3b65aca42758f8be46ca)を試したところ、以下のようになりました。

pre-rotated & half-width のうち、
8950..9353 :: グリフあり。\CID{} は上手く動いている。
10185..10195, 13295..13319 :: グリフなしに見える。空白になる。

![image](https://github.com/trueroad/HaranoAjiFonts/assets/3814120/333ed8ab-bd74-4dff-ae02-66bdad5daef0)

**Comment by t-tk** [comment]
IBM Plex v6.3.0 の IBMPlexSansKR は、Adobe-KR-9 のようです。
japanese-otf(-uptex) の \CIDK{} は Adobe-Korea1-2 を想定しているのでまともに動きませんでした。
Adobe-KR-9 にはそもそも half-width も pre-rotated も入っていないようです。

**Comment by trueroad** [comment]
まだタグを振っただけですが 20230610 版で対応したつもりです。
動作確認などしていただけますでしょうか。
https://github.com/trueroad/HaranoAjiFonts/releases/tag/20230610
https://github.com/trueroad/HaranoAjiFontsCN/releases/tag/20230610
https://github.com/trueroad/HaranoAjiFontsTW/releases/tag/20230610
https://github.com/trueroad/HaranoAjiFontsK1/releases/tag/20230610

KR は回転グリフが無いので本件とは関係ありませんがリリースはしています。
https://github.com/trueroad/HaranoAjiFontsKR/releases/tag/20230610

**Comment by t-tk** [comment]
ありがとうございます。下に貼ったキャプチャのように、期待通り動作しています。

いくつか気づいた点です。
仕様ということで非対応でも構わないものと思います。

(1) TW の Yen sign
“¥” U+00A5 に相当すると思われるグリフが以下のようにあります。
TW (Adobe-CNS) CID+13652(H), CID+17510(V)
CN (Adobe-GB) CID+817(H), CID+22229(V), ( CID+22354(H), CID+29060(V) これはproportionalか? )
JP (Adobe-Japan) CID+291(H), CID+9010(V)

TWのCID+13652(H), CID+17510(V)は、今回非搭載のようですが、JPのCID+291(H), CID+9010(V)で代用してもよいように思います。

(2) JPの欠けグリフ
CID+233, CID+238, CID+295, CID+325 とその pre-rotated は、おそらくもとになるグリフがないのでしょう。
欠けるのは気になりましたがやむを得ないものと思います。

(3) ユーロ記号の半角
CN( Adobe-GB), TW (Adobe-CNS) には、ユーロ記号の半角グリフの割り当てがあるが、非搭載のようです。
これもおそらくもとになるグリフがないのでしょう。
欠けるのは気になりましたがやむを得ないものと思います。


![image](https://github.com/trueroad/HaranoAjiFonts/assets/3814120/d59ac260-82fe-49e7-9d05-401461c263c7)

**Comment by trueroad** [comment]
ご確認いただきありがとうございます。
原ノ味フォント 20230610 版をリリースしました。

> (1) TW の Yen sign
> “¥” U+00A5 に相当すると思われるグリフが以下のようにあります。
> TW (Adobe-CNS) CID+13652(H), CID+17510(V)
> CN (Adobe-GB) CID+817(H), CID+22229(V), ( CID+22354(H), CID+29060(V) これはproportionalか? )
> JP (Adobe-Japan) CID+291(H), CID+9010(V)
>
> TWのCID+13652(H), CID+17510(V)は、今回非搭載のようですが、JPのCID+291(H), CID+9010(V)で代用してもよいように思います。

これはたぶん[ac17-gsub.fea](https://github.com/adobe-type-tools/Adobe-CNS1/blob/master/GSUB/ac17-gsub.fea)の `hwid`, `fwid`, `pwid` に該当のグリフが登録されていないからではないかと思います。

[UniCNS-UTF32-H](https://github.com/adobe-type-tools/cmap-resources/blob/master/Adobe-CNS1-7/CMap/UniCNS-UTF32-H) によると
U+00A5 -> AC1 CID+260
になります。AC1 CID+260 は AC1 規格の [Glyph Set Widths](https://github.com/adobe-type-tools/Adobe-CNS1#glyph-set-widths) によると全角幅です。
一方で、 ac17-gsub.fea を見ると AC1 CID+260 はどこにも登録されていません。本来であれば恐らく `hwid` （半角幅のグリフを得る）に
AC1 CID+260 -> AC1 CID+13652
の変換が、 `fwid` （全角幅のグリフを得る）に
AC1 CID+13652 -> AC1 CID+260
の変換が登録されている必要があるのではないかと思います。

[原ノ味フォント生成プログラム](https://github.com/trueroad/HaranoAjiFonts-generator)は、 ac17-gsub.fea の `hwid`, `fwid`, `pwid` を見て、AC1 における半角・全角・プロポーショナルの相互関係を取得しているため、ここに登録されていないものは紐づけできません。

なお、SourceHanSansTW 2.004 の中身を見ると、cmap テーブルより
U+00A5 -> AI0 CID+100
になっており、AI0 CID+100 は hmtx テーブルを見るとプロポーショナルです。GSUB の `hwid` には
AI0 CID+100 -> AI0 CID+63259
という変換があり、同様に `fwid` には
AI0 CID+100 -> AI0 CID+59210
という変換があるので、グリフとしては半角・全角・プロポーショナルが揃っているようです。

**Comment by t-tk** [comment]
なるほど。ac17-gsub.fea に全角幅、半角幅の対応が載っていない所為で、原ノ味フォント生成プログラムの紐づけ対象外になっている、ということですね。
ac17-gsub.fea の方に対応依頼するのが筋だと理解しました。

リリースありがとうございました。本件は閉じます。
