### ISSUE TITLE
Fontspec files HaranoAji{Mincho,Gothic}.fontspec not distributed since 20230223

### ISSUE THREAD

**Issue by muzimuzhi** [trueroad/HaranoAjiFonts#11]
According to the README, fontspec files `HaranoAji{Mincho,Gothic}.fontspec` are part of the CTAN package [`haranoaji`](https://ctan.org/pkg/haranoaji). But currently they are not found in the package content https://mirrors.ctan.org/fonts/haranoaji.zip.

TeX Live svn [r66086](https://tug.org/svn/texlive?revision=66086&view=revision) shown that they were removed in release 20230223.

These two files are still part of the `trueroad/HaranoAjiFonts-generator` repository so this might be a packing issue.
- [`HaranoAjiGothic.fontspec`](https://github.com/trueroad/HaranoAjiFonts-generator/blob/9e4ddc6dc03e7e483117f255efee3b07768007e3/tex/HaranoAjiGothic.fontspec)
- [`HaranoAjiMincho.fontspec`](https://github.com/trueroad/HaranoAjiFonts-generator/blob/9e4ddc6dc03e7e483117f255efee3b07768007e3/tex/HaranoAjiMincho.fontspec)

First reported in https://github.com/CTeX-org/ctex-kit/pull/710.

**Comment by muzimuzhi** [comment]
I found no clues in changes made between releases 20220220 and 20230223:
- https://github.com/trueroad/HaranoAjiFonts/compare/20220220...20230223
- https://github.com/trueroad/HaranoAjiFonts-generator/compare/20220220...20230223

**Comment by trueroad** [comment]
You are right, it is a packaging issue. I have re-packaged it and uploaded it to CTAN.
Thank you.

**Comment by trueroad** [comment]
The fixed package has been uploaded to CTAN.
https://www.ctan.org/ctan-ann/id/mailman.8222.1713852961.3764.ctan-ann@ctan.org

The fontspec files are now back in TeX Live.
https://tug.org/svn/texlive?revision=71051&view=revision

**Comment by muzimuzhi** [comment]
Many thanks!
