### ISSUE TITLE
HaranoAji CK版

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFonts#2]
TeX Forum の質疑[upLaTeXで「䴩」が文字化け](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2820)を見てふと思ったのですが、
原ノ味フォントと同様にSourceHanSans/SourceHanSerifを Adobe-GB1-5, Adobe-CNS1-7, Adobe-Korea1-2相当にした簡体中国語、繁体中国語、韓国語otfを実現できると嬉しいです。
おそらく開発には大変な労力がかかると想像しますが。

**Comment by trueroad** [comment]
私は中国語や韓国語がわからないので、できたとしても良し悪しの判断ができませんし、なかなか難しいと思います。

一応、当初から中国語や韓国語への転用を意識した作りにしてきたつもりなので、日本語の原ノ味フォント初版(20190303)程度のものであれば、さほど大きな手間をかけずにできるのではないかと思います。ですが、実際に試したわけではないので何とも言えません。また、初版以降では日本語に特化した処理の追加で改良を図ったところも多く、初版以降と同等にするのは難しいです。
例えば、日本語については源ノフォントのグリフ名とAJ16全漢字との対応表 `aj16-kanji.txt` が配布されているので、原ノ味フォント20190309以降ではこれを使ってAJ16全漢字グリフ対応を実現しています。ちょっと探してみた限りではありますが、残念ながら他の言語版の同じような対応表を見つけることができなかったため、このような全漢字グリフ対応は非常に困難と思います。

**Comment by t-tk** [comment]
解説有難うございます。私の想像よりもさらに困難と感じました。
前述のTeX Forum の質疑の例では、`\UTFC{}`でUnicode指定で簡体中国語フォントにアクセスすればよいのでフォント側のグリフの並べ替えは不要でした。
`\CIDC{}`が必要な場面は日本語に比べてはるかに少ないでしょうし、労力の割には報われない気もしてきました。
別案として、`japanese-otf(-uptex)` と似た機能で Unicode指定やSourceHanを想定したパッケージ・vf を作る方向でも考えてみます。

**Comment by trueroad** [comment]
実験的に中国語簡体字(CN)、中国語繁体字(TW)、韓国語(KR)版を作ってみました。私自身、中国語や韓国語がわからないため、良し悪しの判断ができず、どこまで使えるか疑問ではあります。

* https://github.com/trueroad/HaranoAjiFontsCN
* https://github.com/trueroad/HaranoAjiFontsTW
* https://github.com/trueroad/HaranoAjiFontsKR

**Comment by aminophen** [comment]
（私も良し悪しはわかりませんが）素晴らしい試みです。

韓国語は Adobe-KR でよいのでしょうか？ 確かに最近の Adobe は Adobe-Korea1 を事実上やめて Adobe-KR を開発しているようではありますが，巷に出回っている PDF ツールは Adobe-KR 未対応では？と思います。

**Comment by t-tk** [comment]
有難うございます。既に大きな成果だと思います。ここをReopenさせていただきます。
完成度などの判断や評判は使用する人が増えてきて声が上がってくれば自然と分かってくると思います。
私は韓国語の勉強を始めて5年程度になったので以前よりは分かってきました。

Source Han Sansのハングルの文字幅は全角ではなく少し細いと聞いたような記憶があります。
↓に見えるサンプルでもハングルの幅は漢字よりも狭く見えます。
https://blog.typekit.com/alternate/source-han-sans-jp/

otfパッケージ(japanese-otf)の`\UTFK{}`は、Adobe-Korea1の全角幅を前提としているので、それとの組み合わせは文字のデザインと合わなくなるでしょう。
https://github.com/texjporg/japanese-otf-mirror/issues/11 にも書いたのですが、むしろAdobe-KRに合わせた新しいvf,tfm,マクロパッケージを開発するのが方向性としては正しいと思っていました。HaranoAjiFontsKRはその助けになるような気がします。つまり、以前書いたような「Adobe-KR-9 のフリーで有用なフォント」にHaranoAjiFontsKRが該当することになると思います。
いくつか積み上がっている課題が他にもあるので、そちらが片付いたらAdobe-KR+HaranoAjiFontsKRのマクロ作成を試みようかと思います。

**Comment by trueroad** [comment]
> 韓国語は Adobe-KR でよいのでしょうか？ 確かに最近の Adobe は Adobe-Korea1 を事実上やめて Adobe-KR を開発しているようではありますが，巷に出回っている PDF ツールは Adobe-KR 未対応では？と思います。

Adobe-Korea1 版も作ろうかとは思ったのですが GSUB 情報を見つけることができなかったため見送りました。
Adobe-KR ならば
https://github.com/adobe-type-tools/Adobe-KR/blob/master/GSUB/akr9-gsub.fea
で公開されていたので、これを使っています。

GSUB が無くてもフォントを作ることはできるのですが、縦書きや横幅の異なるグリフを結びつけることができなくなるため、かなりの抜けが出てしまうだろうと思っています。

**Comment by trueroad** [comment]
> Source Han Sansのハングルの文字幅は全角ではなく少し細いと聞いたような記憶があります。

Adobe-KR では幅の仕様が Monospaced とされていて具体的には指定されていないものがあるのですが、もしかしたらそれがハングルなのかもしれません。今回の原ノ味フォントKRでは Monospaced は全角幅に統一し、グリフの位置を中央揃えにしてしまっています。

また、CN や TW はあまり悩まず比較的簡単に作ることができたのですが、KR は一筋縄ではいかなかったところがいくつか発生しました。とりあえず何とかできたところ（cmap format 4 のサイズ、GSUB の chain context）もありますが、まだ GPOS の変換がうまくできないようで仕方なくテーブル丸ごと削除しています。

**Comment by t-tk** [comment]
> 今回の原ノ味フォントKRでは Monospaced は全角幅に統一し、グリフの位置を中央揃えにしてしまっています。

japanese-otf の `\UTFK{}`用として組版結果が崩れないことを主眼にするなら全角幅統一がよいと思います。 `\CIDK{}` は、出てくるグリフがAdobe-Korea→Adobe-KRに変わる訳ですね。
Monospaced をフォントのデザインもレイアウトも合わせたものにするにはvf,tfmも整合させる必要があるのでそこで足並みを揃えればよいと思います。

**Comment by t-tk** [comment]
https://github.com/adobe-type-tools/Adobe-KR の README.md に見える

Monospaced 109, 170–3000, 3053–3056, 3059–11450, 12108–12150, 12237–13500

は、https://github.com/adobe-type-tools/Adobe-KR/blob/master/Adobe-KR-9.pdf をざっと見ていると大部分(もしかして全部)はハングルですね。漢字はFullwidthです。
私の想像では Fullwidthの幅とMonospacedの幅の比率がフォントによって異なるのだと思っています。Source Hanの中ではさすがに統一されているんじゃないかなと想像しています。

もう一つよく分からないのは、ハングルの縦組みです。現代韓国語では格段に縦組みの需要が減っているのは確かですがゼロではないので。縦長の字形で縦組みすると読みづらい結果が予想されるのでSource Hanはどうしているのか?

**Comment by trueroad** [comment]
> Adobe-Korea1 版も作ろうかとは思ったのですが GSUB 情報を見つけることができなかったため見送りました。

と言っていたそばから見つけてしまいました。
AJ1のGSUBがgithubに掲載される前の、原ノ味フォント20190324版
https://github.com/trueroad/HaranoAjiFonts-generator/blob/20190324/README.md#ファイル
で使っていたGSUB情報が掲載されているblogにAK1のGSUB情報も一緒に置いてありました…。

というわけで材料は揃ってしまったのでそのうちAK1版もつくってみようかと思います。
フォント名のサフィックスにKRを使ってしまったので、Adobe-Korea1版のサフィックスはK1にするか、Adobe-KR版のサフィックスをAKRに変更してAdobe-Korea1版のサフィックスをAK1にするか…どうしましょうかねぇ…。

**Comment by trueroad** [comment]
> japanese-otf の \UTFK{}用として組版結果が崩れないことを主眼にするなら全角幅統一がよいと思います。 \CIDK{} は、出てくるグリフがAdobe-Korea→Adobe-KRに変わる訳ですね。
> Monospaced をフォントのデザインもレイアウトも合わせたものにするにはvf,tfmも整合させる必要があるのでそこで足並みを揃えればよいと思います。

AK1は全角・半角・プロポーショナルの3種類しか規定がなくて、ハングルは全角になっているという理解でよいでしょうか。AK1版の原ノ味フォントも作ろうと思えば作れそうになってきたので、AK1版は全角で上書きして中央揃え、AKR版は元のSourceHanの幅を踏襲して全角より少し狭い等幅、というのがいいのかもしれないなと思いました。

> 私の想像では Fullwidthの幅とMonospacedの幅の比率がフォントによって異なるのだと思っています。Source Hanの中ではさすがに統一されているんじゃないかなと想像しています。

Adobe謹製のAKR9フォント SourceHanSerifAKR9-Bold.otf と SourceHanSerifAKR9-Regular.otf が
https://github.com/adobe-type-tools/Adobe-KR/releases
でダウンロードできるので、中身をのぞいて見てみたところ Monospaced の幅は 966 で統一されているようでした。（全角は 1000）

普通の SourceHanSerifKR では、上記と同じ Unicode に割り当たっている CID のグリフの幅は同じ 966 のようですが、普通の SourceHanSansKR では 920 になっているみたいです。

> もう一つよく分からないのは、ハングルの縦組みです。現代韓国語では格段に縦組みの需要が減っているのは確かですがゼロではないので。縦長の字形で縦組みすると読みづらい結果が予想されるのでSource Hanはどうしているのか?

縦組みをあまりしないというのは知りませんでした。JP, CN, TWに比べるとKRはGPOS/GSUBが格段に複雑なので、その辺で何かしているのかもしれませんが、よくわかりませんでした。

**Comment by t-tk** [comment]
Adobe-Korea1の文字幅は [5093.Adobe-Korea1-2.pdf](https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5093.Adobe-Korea1-2.pdf)の"Glyph Set Widths"のところに記載があり、

> The following table provides CID ranges that explicitly indicate which glyphs are intended to be designed with proportional- or half-width set widths. All other glyphs are expected to be full-width.

ハングル完成形や漢字を含む大多数のグリフが全角ということで間違いないと思います。

`SourceHanSerifAKR9-....otf` と普通の `SourceHanSerifKR` とでハングルのグリフの幅が違っているということですか、意外です。グリフそのもののデザインも違うのか、詰め幅を変えているのでしょうか? AKRであるならばハングルは 966 の幅に統一すべしということなのか、よく分かりません。

サフィックスについては好みがあると思います。以下は全くの個人の感想です。
"CN", "TW"は国家や地域の名称が見えすぎていて政治的に敏感な方面から否定的な反応をもらうかもしれないという不安は少しあります。Adobeが"GB"とか"CNS"とか規格名をもってきたり"simlified chinese", "traditional chinese"と呼んだりしているのもそういう事情があると思います。
しかし、短くて判りやすいサフィックスというのも難題で、uptex-fontsでは"jpn", "sch", "tch", "kor"にしましたがどうでしたか。
"AKR"は、他が"A"を含んでいないので重い印象です。他が2文字ならば"KR" (Adobe-KR), "K1" (Adobe-Korea1) がすっきりしていると思います。

> 縦組みをあまりしない

韓国では現在の書籍、雑誌、新聞はほぼ100%横組みです。本の背表紙は横組みと縦組みが混在しています。書籍の本文中に縦組みを使っている例もたまに見かけますが例外的です。街の看板でも縦組みを見かけます。北朝鮮もそうだと思います。大陸中国もそうだと聞いています。台湾は縦組みの出版物がまだ多いと聞いたような気がします。

**Comment by t-tk** [comment]
そういえば"AKR"ではHaranoAjiの"A"と重複しますね。

別案です。他が2文字ならば"KR" (Adobe-KR), "KO"または"Ko" (Adobe-Korea1)

**Comment by t-tk** [comment]
> AK1版は全角で上書きして中央揃え、AKR版は元のSourceHanの幅を踏襲して全角より少し狭い等幅

私のイメージも大体そうでした。
もう少し細かく言うと、AKR版の中でハングルは全角より少し狭い等幅(Monospaced)、漢字は全角(Fullwidth)という区分を明確にする。
AK1版はjapanese-otfの`\UTFK{}`, `\CIDK{}`で全角で使用、AKR版はこれから開発する新しいマクロでハングルと漢字の幅を区分して使用するようなイメージです。

**Comment by trueroad** [comment]
> Adobe-Korea1の文字幅は...
> ハングル完成形や漢字を含む大多数のグリフが全角ということで間違いないと思います。

やっぱりそうなんですね。ありがとうございます。

> SourceHanSerifAKR9-....otf と普通の SourceHanSerifKR とでハングルのグリフの幅が違っているということですか、意外です。グリフそのもののデザインも違うのか、詰め幅を変えているのでしょうか? AKRであるならばハングルは 966 の幅に統一すべしということなのか、よく分かりません。

あ、いえ、`SourceHanSerifAKR9-*.otf` と `SourceHanSerifKR-*.otf` は 966 で同じです。違うのは `SourceHanSansKR-*.otf` で 920 になっています。Serif と Sans で違うということです。

> サフィックスについては好みがあると思います。以下は全くの個人の感想です。
> "CN", "TW"は国家や地域の名称が見えすぎていて政治的に敏感な方面から否定的な反応をもらうかもしれないという不安は少しあります。Adobeが"GB"とか"CNS"とか規格名をもってきたり"simlified chinese", "traditional chinese"と呼んだりしているのもそういう事情があると思います。

CN, TW は SourceHan のサフィックスをそのままもらってきたものなので、Adobe でもそういうのを使うこともあるということだと思います。
また、簡体字の SourceHan は CN だけなので SC に変えてもいいかなと思ったのですが、繁体字の SourceHan は TW と HK の 2 種類あります（HK は Sans のみ）。TW と HK 双方とも繁体字で Adobe-CNS1 に対応するのだと理解しています。ですが、個々のグリフがどう対応するのかまったく知識がないのと、Serif と Sans 双方揃っているのが TW だけなので、SourceHanSerifTW と SourceHanSansTW をベースにして HaranoAjiFontsTW を作った、という次第です。この辺の対応関係がクリアにできれば CN, TW ではなくて SC, TC の方がいいように思います。

> しかし、短くて判りやすいサフィックスというのも難題で、uptex-fontsでは"jpn", "sch", "tch", "kor"にしましたがどうでしたか。

3文字ならばそうなんだと思います。2文字ならJP, SC, TC, KR ですよね。

> 韓国では現在の書籍、雑誌、新聞はほぼ100%横組みです。本の背表紙は横組みと縦組みが混在しています。書籍の本文中に使っている例もたまに見かけますが例外的です。街の看板でも縦組みを見かけます。北朝鮮もそうだと思います。大陸中国もそうだと聞いています。台湾は縦組みの出版物がまだ多いと聞いたような気がします。

ほとんど使わないのと、縦組みしても1行しかないのであれば幅が狭くてもあまり気にならない、ということかもしれませんね。

> "AKR"は、他が"A"を含んでいないので重い印象です。他が2文字ならば"KR" (Adobe-KR), "K1" (Adobe-Korea1) がすっきりしていると思います。

> そういえば"AKR"ではHaranoAjiの"A"と重複しますね。
> 別案です。他が2文字ならば"KR" (Adobe-KR), "KO"または"Ko" (Adobe-Korea1)

Adobe-KR はサフィックス KR のまま、
Adobe-Korea1 はサフィックス K1, KO, Ko のいずれかでどうだろうか、ということですね…。

> もう少し細かく言うと、AKR版の中でハングルは全角より少し狭い等幅(Monospaced)、漢字は全角(Fullwidth)という区分を明確にする。
> AK1版はjapanese-otfの\UTFK{}, \CIDK{}で全角で使用、AKR版はこれから開発する新しいマクロでハングルと漢字の幅を区分して使用するようなイメージです。

AKR 版のハングルは、どのフォントを使うかで横幅が違うのが厄介ですね。

**Comment by t-tk** [comment]
> Serif と Sans で違う

ああなるほど。今私が想定しているのはuplatexでvf,tfmを作って使うやり方です。SerifとSansでそれぞれの文字幅に合わせたvf, tfmを作ればよい訳ですし、SourceHanシリーズまたはHaranoAji多言語版シリーズにターゲットが絞れていてMonospacedの幅が書体毎(ファミリー毎)に固定されていればSerifとSansに差があっても対応出来そうです。

AKR汎用を目指すのは難しくなりますが、Monospacedの幅がフォントごとに異なるならばもともと無理だったとも言えます。

**Comment by t-tk** [comment]
> CN, TW は SourceHan のサフィックスをそのままもらってきた

分かりました。先程の私の見解は取り下げます。どうかお気になさらぬよう。

**Comment by t-tk** [comment]
私のところの[japanese-otf-uptex](https://github.com/t-tk/japanese-otf-uptex)で[\UTFC{}, \UTFT{}, \UTFK{}の多書体化](https://github.com/t-tk/japanese-otf-uptex/issues/4)を検討中です。
ハングルは HaranoAjiFonts KR の現状の全角幅です。2文字程度なら違和感ないですね。長い文章になると文字幅のデザイン差が顕著に見えてくるかもしれません。

![Screenshot from 2020-05-23 19-25-17](https://user-images.githubusercontent.com/3814120/82728507-8d6b5e80-9d2b-11ea-8137-eeb2e0689407.png)

**Comment by trueroad** [comment]
原ノ味フォント 20200524 版をリリースしました。

今回から Adobe-Korea1 に対応した K1 を追加しています。ハングルは全角幅です。
https://github.com/trueroad/HaranoAjiFontsK1

KR は前回と同じ Adobe-KR 対応です。Monospaced のグリフ（ハングル）について前回は全角幅でしたが、今回は AKR CID+221 (U+AC00) の幅と同じになるようにしています（全角より狭くなります）。

CN, TWは前回の版で GPOS がおかしかったのを修正しています。KR は今回も GPOS を付けていません（やはり付けると Windows がフォントとして認識してくれない）。K1 は CN, TW と同じく GPOS 付きで問題なかったので付けてあります。

**Comment by t-tk** [comment]
ありがとうございます。
japanese-otf-uptex の [\UTFC{}, \UTFT{}, \UTFK{}の多書体化](https://github.com/t-tk/japanese-otf-uptex/issues/4) では K1 を利用させていただき、新しい AKR版は別途 14書体をすべて使う新セットを開発・利用させていただこうかと思っています。

**Comment by t-tk** [comment]
お世話になります。
japanese-otf-uptex の新版 [v0.26](https://github.com/t-tk/japanese-otf-uptex/releases/tag/v0.26), [2020-11-14](https://github.com/texjporg/japanese-otf-mirror/releases/tag/2020-11-14)をリリースしました。
サンプルのmapファイルで HaranoAji {CN,TW,K1} を利用させていただきました。

Haranoaji CK版のおかげでCJK多言語多ウェイト化が手軽に実現できるようになりました。
ありがとうございました。

**Comment by t-tk** [comment]
いずれ HaranoAji {CN,TW,KR} を利用させていただいて japanese-otf{,-uptex}に似た新パッケージを作ろうかと考えていますが、ここでのお願いはひとまず完了したのでここは閉じます。
お世話になりました。ありがとうございました。
