### ISSUE TITLE
原ノ味 P明朝 ・Pゴシック

### ISSUE THREAD

**Issue by tani** [trueroad/HaranoAjiFonts#3]
こんにちは．このプロジェクトによりTeXLive 2020からどのTeX処理系でも多ウェイトのフォントが使えるようになり感謝しています．

私は現在LaTeXで和文プロポーショナル組について調べています．調べた結果以下のような現状だと理解しました．
- (u)pTeXにおいて**簡単に**和文プロポーショナル組ができるのは，macOSのヒラギノフォントだけである (`otf`パッケージで`deluxe`オプションを付け，`\propshape`コマンドでプロポーショナル仮名を使う．)
- LuaTeXで**綺麗に**和文プロポーショナル組できるのは，源真ゴシックPのようなプロポーショナル組が前提のフォント(JFMで`prop`を指定する．)か，または遊明朝のようなOTFの`pwid`フィーチャを持つフォント(CharacterWidthでProportionalを指定する．)

ところで，このプロジェクトの上流プロジェクトである源ノ明朝・角ゴシックではOTFの`palt`フィーチャしか持っていないため，和文プロポーショナル組が綺麗にできないそうです．([TeXでつくるプロポーショナル組日本語文書](https://qiita.com/zr_tex8r/items/0512dd43e9806483013a#%E5%8D%98%E7%B4%94%E3%81%AAopentype%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88%E3%81%A7%E3%83%97%E3%83%AD%E3%83%9D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E7%B5%84%E6%BA%90%E7%9C%9F%E3%82%B4%E3%82%B7%E3%83%83%E3%82%AFp))

そこでユーザとしてデフォルトのフォントで和文プロポーショナル組が可能であれば嬉しいので，ここにてリクエストすることにしました．以下が考えられる方針です．

- LuaTeX用
   - OTFの`pwid`属性を追加する (どこから?)
   - もしくは，原ノ味 P明朝 ・Pゴシックとして別のフォントを作る (源真ゴシックPが参考になるかもしれないです)
- (u)pTeX用
   - ヒラギノのようにフォントメトリックを追加し，`otf`パッケージで切り替えられるようにする．([Enhancement of CJK proportional font ](https://github.com/texjporg/tex-jp-build/issues/8))
   - `hiraprop`のような従属欧文用のパッケージははなくてもSource Serif ProやSource Sans Proがあるから大丈夫．

生成スクリプトの改善だけではどうしようもなさそうですが，マイルストーンのひとつとして考えてもらえますでしょうか?

**Comment by trueroad** [comment]
たまたまですが、ちょうど本日夕方にリリースした原ノ味フォント 20200524 版でプロポーショナルかなを追加してあり、`pwid` で使えるようになっています。LuaTeX ではなくて XeTeX （XeLaTeX でもなくて plainXeTeX）での例ですが、
https://github.com/trueroad/HaranoAjiFonts-generator/blob/20200524/tex/test-palt_to_pwid.xetex.tex
が以下の PDF のようになります。 LuaTeX でも同様のことができると思います。
[test-palt_to_pwid.xetex.pdf](https://github.com/trueroad/HaranoAjiFonts/files/4673674/test-palt_to_pwid.xetex.pdf)

(u)pTeX でプロポーショナルかなを使うには、フォント毎ウェイト毎に横幅が異なってしまうため、 jfm 等それぞれに専用のものを用意（原ノ味なら全 14 組）して切り替える必要があり、そう簡単にはいかないと思います。ヒラギノで簡単にできるのは、そういう jfm 等を用意された方がいらっしゃるということだと思います。

**Comment by tani** [comment]
> たまたまですが、ちょうど本日夕方にリリースした原ノ味フォント 20200524 版でプロポーショナルかなを追加してあり、pwid で使えるようになっています。LuaTeX ではなくて XeTeX （XeLaTeX でもなくて plainXeTeX）での例ですが、
https://github.com/trueroad/HaranoAjiFonts-generator/blob/20200524/tex/test-palt_to_pwid.xetex.tex
が以下の PDF のようになります。 LuaTeX でも同様のことができると思います。
test-palt_to_pwid.xetex.pdf

なんということでしょう! すばらしいです．結構な作業だったと思われますが，ご苦労さまでした．

> (u)pTeX でプロポーショナルかなを使うには、フォント毎ウェイト毎に横幅が異なってしまうため、 jfm 等それぞれに専用のものを用意（原ノ味なら全 14 組）して切り替える必要があり、そう簡単にはいかないと思います。ヒラギノで簡単にできるのは、そういう jfm 等を用意された方がいらっしゃるということだと思います。

冒頭でも引用しましたが，一先ずフォントメトリックを取得するだけならば，すでにOTFから自動で抽出するスクリプトがあるようなので，全ウェイトからフォントメトリックは抽出できそうなのですが，他に考えられる懸念事項というのはありますでしょうか? 例えば，取得したフォントメトリックを手で調整する必要があったりしますか．

> ttf2tfm なるものがあるのですね。さらに調べてみると lcdf-typetools のなかに otftotfm なるものが入っていることも気づきました。
> 
> ところで私が先に出した「IPA P 明朝」の JPL ソースは，propw を使って自動生成したものです。propw.exe は dviout の中に入っていて，「Windows API (GDI32) の機能で pTeX が扱える仮名や記号のメトリックを取得し，JPL ファイルに書き出すもの」です。
> 
> (引用元: https://github.com/texjporg/tex-jp-build/issues/8#issuecomment-310904865)

**Comment by trueroad** [comment]
> 冒頭でも引用しましたが，一先ずフォントメトリックを取得するだけならば，すでにOTFから自動で抽出するスクリプトがあるようなので，全ウェイトからフォントメトリックは抽出できそうなのですが，他に考えられる懸念事項というのはありますでしょうか? 例えば，取得したフォントメトリックを手で調整する必要があったりしますか．

手動調整しなくても LuaTeX/XeTeX と同じような組み方ならできるのではないかと思います。ヒラギノのプロポーショナルかなを実現しているOTFパッケージを眺めていると大変そうだなぁという感じがしている、というぐらいです。普段からjfmを作成されているような方であれば、特に問題のない作業なのかもしれません。

**Comment by trueroad** [comment]
本件は原ノ味フォント 20200524 版で解決していると思いますのでクローズします。

**Comment by tani** [comment]
そうですね。対応ありがとうございました！

**Comment by trueroad** [comment]
pLaTeX/upLaTeX で原ノ味フォントのプロポーショナルかなを使うことができるパッケージを作っていただいたので、紹介しておきます。
https://github.com/zr-tex8r/PXharapro
