### ISSUE TITLE
HaranoAjiMincho-RegularはU+FF0D（－）が豆腐？

### ISSUE THREAD

**Issue by tsuu32** [trueroad/HaranoAjiFonts#4]
こんにちは。原ノ味明朝を使っていて気づきました。
利用しているのはTeX Liveでインストールされたもので、バージョンは「HaranoAjiMincho-Regular version 20200418;ttx 4.7.0」です（macOSのFont Bookより）。

macOSのFont Bookで原ノ味明朝 Regularを見てみたり、テキストエディット.appで原ノ味明朝を試してみたりしましたが、どうやら原ノ味明朝 Regularでは「U+FF0D（－）」が存在しない（？）ようです。
（U+FF01...U+FF9Fを見てみたところ、U+FF0D（－）だけ欠けているようでした）

また、以下のような文書を`luatex`で処理しても、生成されたPDFで「－」が豆腐になることを確認しました。

```
\input luatexja.sty

日本語－

\bye
```

UniJIS2004-UTF16-Hによると、U+2212とU+FF0DはどちらもAJ1 CID+693であり、これが関係してるのかもしれませんが詳しくはわかりません。

これは修正可能でしょうか。

**追記**
最新版（HaranoAjiMincho-Regular version 20200524;ttx 4.10.2）でもU+FF0D（－）が豆腐であることを確認しました。

**Comment by trueroad** [comment]
原ノ味明朝、原ノ味角ゴシックともに、 cmap テーブルに U+FF0D が無いことを確認しました。使用頻度はそれなりに高いコードポイントだと思われますし、対応するグリフである AJ1 CID+693 自体は搭載していますので、次期リリースではなんらかの対応を考えたいと思います。

なお、pTeX/upTeX で普通の使い方をする（cmap テーブルではなくて CMap ファイルを使う）場合はこのような問題は発生しないものと思います。

原因ですが、元の源ノ明朝の cmap テーブルは、

* U+2212 → AI0 CID+824
* U+FF0D → AI0 CID+59956

となっていて、別々の AI0 CID が割り当てられています。
ですが、変換先の AJ1 では仰せの通り U+2212, U+FF0D どちらも AJ1 CID+693 になっていて重複しています。重複しているため AI0 CID から AJ1 CID への変換テーブルを作成する際に、どちらの AI0 CID を AJ1 CID+693 に割り当てるか判断します。今回の場合は、AI0 CID+824 の方が優先される結果となり、

* AI0 CID+824 → AJ1 CID+693
* AI0 CID+59956 →破棄

という変換テーブルが生成されます。この変換テーブルを用いて源ノ明朝の cmap テーブルを変換すると、

* U+2212 → AI0 CID+824 → AJ1 CID+693
* U+FF0D → AI0 CID+59956 →破棄

ということになって U+FF0D が消えてしまう、というものです。原ノ味角ゴシックでも AI0 CID が微妙に違いますが、同様の事象により U+FF0D が cmap テーブルから消えてしまっています。

この U+FF0D が消えてしまうのは、あくまでも変換した cmap テーブル、つまり原ノ味明朝・原ノ味角ゴシックの cmap テーブルから消えているというだけで、 AJ1 CID+693 は搭載されています。ですので、 pTeX/upTeX で CMap ファイルを用いる場合には cmap テーブルが使われませんので U+FF0D を問題なく使うことができます。

**Comment by tsuu32** [comment]
ありがとうございます。原ノ味フォントの生成方法に詳しくなかったので私には原因がわかりませんでしたが、原因がはっきりしてるようで良かったです。

> なお、pTeX/upTeX で普通の使い方をする（cmap テーブルではなくて CMap ファイルを使う）場合はこのような問題は発生しないものと思います。

はい。そうだと思います。~また、`lualatex`でも豆腐になりませんでした。~

私が問題に気づいたのはTexinfoを用いたときです。`PDFTEX=luatex texi2pdf foo.texi`としたとき、これは`luatex`の例と同様なのでU+FF0dが文字化けしていて気づきました。

**Comment by trueroad** [comment]
> はい。そうだと思います。また、lualatexでも豆腐になりませんでした。

「豆腐」と仰っているのは、四角の中にバツが入ったような形（.notdef グリフ）ですよね？何か設定が違うのかもしれないですが、luatex でも lualatex でも同じ結果になるはずです。いま手元の環境で試してみましたが、やはり lualatex でも U+FF0D は .notdef になりました。TeX Live 2020 を使っています。

```
\documentclass{ltjsarticle}

\begin{document}

日本語－

\end{document}
```

**Comment by tsuu32** [comment]
> 「豆腐」と仰っているのは、四角の中にバツが入ったような形（.notdef グリフ）ですよね？何か設定が違うのかもしれないですが、luatex でも lualatex でも同じ結果になるはずです。いま手元の環境で試してみましたが、やはり lualatex でも U+FF0D は .notdef になりました。TeX Live 2020 を使っています。

！すみません。「`lualatex`でも豆腐になりませんでした。」というのは私の勘違いでした。（ヒラギノを使ってました...）

`lualatex`でも原ノ味だと確かに .notdef でした。

**Comment by trueroad** [comment]
本日リリースした[20200612 版](https://github.com/trueroad/HaranoAjiFonts/releases/tag/20200612)で修正できていると思います。
ご確認ください。

**Comment by tsuu32** [comment]
新しいHaranoAjiMincho-Regular (HaranoAjiMincho-Regular version 20200612;ttx 4.12.0) を試してみました。
テキストエディット.appやPages.appを使い、原ノ味明朝でU+FF0D（－）が使えることを確認しました。

ありがとうございました！
Closeさせていただきます。
