### ISSUE TITLE
ゴシックの「――」がつながらない

### ISSUE THREAD

**Issue by okumuralab** [trueroad/HaranoAjiFonts#5]
```
\documentclass{ltjsarticle}
\begin{document}

あ――あ

\textgt{あ――あ}

\end{document}
```

で，原ノ味明朝のほうはうまくつながるのですが，原ノ味ゴシックがつながりません：

![dash](https://user-images.githubusercontent.com/3616498/95454076-e835e780-09a6-11eb-8872-d960f523e800.png)

源ノ角ゴシックならうまくいくようです。

**Comment by trueroad** [comment]
ご指摘いただいた現象を確認しました。
源ノだと、つながるというか、私の環境だけかもしれませんがおかしくなってしまいます。

```
\documentclass{ltjsarticle}
\usepackage[sourcehan]{luatexja-preset}
\begin{document}

あ――あ

\textgt{あ――あ}

\end{document}
```

![20201008_sourcehan_dash](https://user-images.githubusercontent.com/3464255/95458035-a14af080-09ac-11eb-9632-b9ebeb418d97.png)

見た感じだけの判断ですが、源ノは「――」があったら GSUB で横が倍の長さの最初からつながっているグリフに置き換えているのではないかと思います。原ノ味は AJ1 準拠なので、そういった特殊なグリフは無くて置き換えも発生せず、元のグリフを 2 つ並べただけになっているものと思います。

**Comment by okumuralab** [comment]
説明不足ですみません。私も源ノはLuaTeX-jaで使うとそうなったので，生のfontspecでやってしまいました。

```
\documentclass{article}
\usepackage{fontspec}
\newfontface{\sourcehansans}{SourceHanSans-Regular}
\begin{document}
\sourcehansans
あ――あ
\end{document}
```

![dash2](https://user-images.githubusercontent.com/3616498/95459374-88dbd580-09ae-11eb-8161-54cedc7c1a12.png)

なるほど，つながっているグリフに置き換えているだけで，元のグリフはゴシックのほうは短いのですね。
理由がわかってすっきりしました。お騒がせして申し訳ありませんでした。

**Comment by trueroad** [comment]
源ノの GSUB テーブルを覗いてみたところ、やはりリガチャが定義されていました。2つ並べたものだけでなく、3つ並べたものにも横に3倍の長さのグリフが別途用意されているようです。

plain LuaTeX ですが、以下のように通常のリガチャが効いているものと、 `ccmp` を無効にしてリガチャが効かないようにしたものと並べてみると、

```tex
\input luaotfload.sty
\nopagenumbers

\font\f{file:SourceHanSans-Medium.otf} \f

あ――あ
あ―――あ

\font\f{file:SourceHanSans-Medium.otf:-ccmp} \f

あ――あ
あ―――あ

\font\f{file:SourceHanSerif-Regular.otf} \f

あ――あ
あ―――あ

\font\f{file:SourceHanSerif-Regular.otf:-ccmp} \f

あ――あ
あ―――あ

\bye
```

![20201008_sourcehan_dash_ligature](https://user-images.githubusercontent.com/3464255/95461931-c68e2d80-09b1-11eb-850d-e7cc0a609cb3.png)

というように、源ノ角ゴシックでも `ccmp` が無効なら途切れてしまいます。また、この PDF を AcrobatReader で開いて文字列を選択してみると、`ccmp` 無効にしたところは1文字ずつバラバラに選択できますが、リガチャが効いているところは2文字分もしくは3文字分がまとめて選択する/しないになるようで、バラバラにはできませんでした。

**Comment by okumuralab** [comment]
なるほど。勉強になりました。ありがとうございました。

**Comment by trueroad** [comment]
いえ、こちらこそ勉強になりました。ありがとうございます。

源ノ角ゴシックは「あ―」間のアキと「―あ」間のアキがccmp有効無効にかかわらずほぼ同じに見えるので、U+2015「―」を並べた場合はリガチャ置き換えでつなげるのを前提にしていて、単体のグリフはもちろんリガチャでつなげたグリフも、見た目を重視して隣のグリフ（ここでは「あ」）に突き刺さって見えないようにワザと短くしているのかなぁ、などと思いました。

あと、luatexjaで「―」と「あ」が重なってしまう件については、
https://osdn.net/projects/luatex-ja/ticket/40846
に報告しておきました。

本件はこれでクローズさせていただきます。
