### ISSUE TITLE
縦組み 「：」が倒れていない

### ISSUE THREAD

**Issue by bogytech** [trueroad/HaranoAjiFonts#6]
縦組にした時に和文(いわゆる全角)の「：」コロンが倒れていないようです。
「；」セミコロンや括弧類はちゃんと倒れているので、これだけ失敗しているように見えます。

**Comment by trueroad** [comment]
「：」コロンの方が 90 度回転して、「；」セミコロンの方が回転しない、のではないでしょうか。

pLaTeX の以下のソースでテストしてみました。

```tate.tex
% -*- coding: utf-8 mode:latex -*-

\documentclass[tate]{jlreq}

\begin{document}

\mcfamily
コロン：
セミコロン；
「カギかっこ」
（丸カッコ）

\gtfamily
コロン：
セミコロン；
「カギかっこ」
（丸カッコ）

\end{document}
```

これを以下のように、原ノ味フォントを使い 2004 字形で PDF にします。

```
$ platex tate.tex
$ dvipdfmx -f ptex-haranoaji-04.map -o tate.haranoaji-04.pdf tate.dvi
```

すると、コロン「：」は横書き用とは異なる 90 度回転したグリフになり、セミコロン「；」は横書き用と同じグリフになりました。ただ、これは原ノ味フォントを使わなくても同じ結果になります。以下のようにしてフォントを埋め込まない PDF を作ります。

```
$ dvipdfmx -f ptex-noEmbed-04.map -o tate.noembed-04.pdf tate.dvi
```

これを Acrobat Reader を使い小塚で代替表示させると、原ノ味を使った時と同じでコロン「：」は横書き用とは異なる 90 度回転したグリフになり、セミコロン「；」は横書き用と同じグリフとなりました。

いずれにせよ、pTeX で小塚を使った時と同様の表示になりますので、コロンとセミコロンで挙動が一致しないのは気持ち悪いのかもしれませんが「そういうものだ」という理解でいます。

**Comment by trueroad** [comment]
GSUB に問題があるか否か確かめるため、XeTeX で以下のソースを試してみました。

```tate-xetex.tex
% -*- coding: utf-8 mode:tex -*-

\nopagenumbers

\def\test{：；「」（）}

\font\f="[HaranoAjiMincho-Regular.otf]" \f
\test
（原ノ味明朝Regular）\par

\font\f="[HaranoAjiMincho-Regular.otf]:+vert" \f
\test
（原ノ味明朝Regular, +vert）\par

\font\f="[HaranoAjiMincho-Regular.otf]:+vrt2" \f
\test
（原ノ味明朝Regular, +vrt2）\par

\font\f="[HaranoAjiGothic-Regular.otf]" \f
\test
（原ノ味角ゴシックRegular）\par

\font\f="[HaranoAjiGothic-Regular.otf]:+vert" \f
\test
（原ノ味角ゴシックRegular, +vert）\par

\font\f="[HaranoAjiGothic-Regular.otf]:+vrt2" \f
\test
（原ノ味角ゴシックRegular, +vrt2）\par

\font\f="[SourceHanSerif-Regular.otf]" \f
\test
（源ノ明朝Regular）\par

\font\f="[SourceHanSerif-Regular.otf]:+vert" \f
\test
（源ノ明朝Regular, +vert）\par

\font\f="[SourceHanSerif-Regular.otf]:+vrt2" \f
\test
（源ノ明朝Regular, +vrt2）\par

\font\f="[SourceHanSans-Regular.otf]" \f
\test
（源ノ角ゴシックRegular）\par

\font\f="[SourceHanSans-Regular.otf]:+vert" \f
\test
（源ノ角ゴシックRegular, +vert）\par

\font\f="[SourceHanSans-Regular.otf]:+vrt2" \f
\test
（源ノ角ゴシックRegular, +vrt2）\par

\bye
```

その結果、
コロンは `vert` だと 90 度回転したグリフになりますが、`vrt2` だと横書き用と同じです。
セミコロンは `vert` でも `vrt2` でも横書き用と同じでした。

`vert` と `vrt2` で一貫性がないとか、コロンとセミコロンで一貫性がないとか、気持ち悪いと言えば気持ち悪いですが、比較対象に示した源ノフォントでもまったく同じ挙動ですので、やっぱり「そういうものだ」という結論になります。

**Comment by bogytech** [comment]
この問題(vrt2 でコロンが倒れない)は元になった「源ノ明朝体」、「NotoSerif」にもあるのですが、市販の明朝体フォントでは発生しません(IPAex明朝でも発生しません)。(vert も vert2 のどちらでもコロンとセミコロンは90度回転した字体になります.)。
「小塚」でも起きるとのことですが、私の環境では小塚明朝体では発生していません(何が違いだろうか、LuaTeX  で直接PDFを作成して確認してみましたが問題はありませんでした)。

**Comment by bogytech** [comment]
書き方が少し悪かったので補足、IPAex明朝には vrt2 が無いので、vert にフォールバックされるため問題は起きないのですが、IPAex明朝から原の味に切り換えた場合に発生に気付いたので括弧書きしました。

**Comment by bogytech** [comment]
あ、セミコロンと比較したから混乱しているのか、申し分けない。セミコロンはそもそも対象外ですね忘れてください。コロンと括弧類に読み変えてください。(要点は vrt2 のコロンは倒れているべきです。じゃないと既存の縦書き文章を原の味に変えた時に内容が変わってしまうので)

**Comment by h20y6m** [comment]
すこし試してみたところ

* TeX Live 2019 frozen (luatexja 2020/03/01): NG
* TeX Live 2020 最新 (luatexja 2020-10-30): OK

でした。

使っている luatexja の問題かもしれません。

**Comment by trueroad** [comment]
TeXフォーラムの「LuaTeX-jaの縦書きの全角コロン」
https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2935
にある通り、全角コロンが縦書きで回転するか否かはフォントによって違うものだと思っています。

LuaTeX-ja では上記にある通り、
https://ja.osdn.net/projects/luatex-ja/scm/git/luatexja/commits/283f0e877dcd39f83aa9533400c14a28d2392f85
で対策（おそらく条件によって `vert` と `vrt2` のどちらを使うか判定するもの）が入ったようなので、LuaTeX-ja 20201001.0 以降ならば回転するようになっているのではないかと思います。

**Comment by trueroad** [comment]
それから `vrt2` は、
https://blogs.adobe.com/CCJKType/2019/07/aj17-gsub-features.html
によると、

> now-deprecated—in favor of UAX #50 (Unicode Vertical Text Layout) compliance—'vrt2' (Vertical Alternates and Rotation) features

だそうなので、今後は使われなくなっていくのではないかと思っています。また、ここで出てくる UAX #50 ですが、さきほどの LuaTeX-ja のコミットメッセージにも uax50 とありますので、こうした流れに対応するものだと思います。

**Comment by bogytech** [comment]
となると、フォントの問題ではなくて luatexja の vrt2 対応が一部バグっていた。そのくせ vrt2 を縦書きのデフォルトに使用していたということでしょうか？
UAX#50 では全角セミコロンと全角コロンは Tr となっており、縦書きグリフが指定されていればそれを使用する。縦書きグリフが未登録ならば横書きグリフを90度回転させて使用するはずです。
一般的な和文フォントだと、全角セミコロンは主に欧文で使うので90度回転でも問題無いので未登録、全角コロンは和文とも一緒に使うので、その場合に単に90度回転させただけのグリフだと少し左にズレてしまうので、90度回転させたグリフを位置調整して中心が揃うようにしたものが縦書き用として登録されているのだけど、この辺が原の味の vrt2 だと異なっているののかな？
ちなみに原の味の vert の全角コロンは回転して位置調整したグリフのように見えます。同じものが vrt2 にも入っているべきなのですが、もし既にそうなっているのにうまく使用できていないのだったら、お騒がせしてすいません。

**Comment by trueroad** [comment]
LuaTeX-ja の縦書きグリフ選択方法には何回か変遷があるようなので、おそらくバージョンによって挙動が微妙に違うのではないかと思います。

https://github.com/trueroad/HaranoAjiFonts/issues/6#issuecomment-742515037
で示した通り、原ノ味の全角コロンは `vert` だと回転するけど `vrt2` だと回転しません。ただ、これは源ノと同じなので「問題ない」と判断しています。

原ノ味は源ノの派生フォントなので、この辺は何か特別な理由がない限り源ノを踏襲しています。

> 同じものが vrt2 にも入っているべき

というお考えなのでしたら、ぜひ、[源ノ角ゴシック](https://github.com/adobe-fonts/source-han-sans)や[源ノ明朝](https://github.com/adobe-fonts/source-han-serif)にその旨の Issue を立てていただければと思います。源ノが対応するのであれば原ノ味も追従します。

あるいは、源ノのような AI0 フォントでは対応する必要がないが、AJ1 フォントだと対応しなければならない何らかの規格などに「同じものが vrt2 にも入っているべき」というような規定があるのであれば、源ノとは関係なく原ノ味側で独自に対応した方がよいということになります。そうであれば、その規格や規定をお示しいただければ対応を検討したいと思います。

**Comment by bogytech** [comment]
Adobe-Japan-1 という話をするのなら、そもそも縦書きグリフが登録されるべき CID が全て未定義になっており、それ以前の問題のように見えます。(CID で直接縦書きグリフにアクセスする人は少ないでしょうから、実用上で問題になることはないと思いますが、あってるかどうかをの議論すらできない状態)。

ということで、Adobe Japan-1 対応でないのは置いておいて、今の仕様で特に問題ない。こういうものだ。他の Adobe-Japan-1 フォントとの違いは仕様であるということならば、このイシューはクローズしてください。お手数をおかけしました。

**Comment by bogytech** [comment]
ついでに、元の源の明朝の実装がどうなっているのか source を確認したので追記しておきます。
源の明朝では vert は言語別に個別の定義を行ない、jp 版ではデフォルトでは各国共通(vert_all)等に加えて日本語のみの縦書きグリフ(vert_jp)が有効になっています(jp版OTFでも lang の切り換えにより他の国のルールにできる)。一方で vert2 では各国共通のもの(vert_all)のみが有効になっており、言語を切り換えても変わらないという実装になっているようです。

でこの日本語対応のルール.(vert_jp)の中身は「全角コロン」だけのようです。つまり vert は日本ルールでコロンの縦書きフリフがあるものの、vert2 は国際ルールでコロンの対応無しという内容です。
日本語以外の言語対応のためにこのような実装にする必要があったのだろうと推測しますが、vert2 は vert のスパーセットであるべきという OpenType の規定を無視してまでこのような実装にしている詳細な理由は不明です。

原の味は日本語専用と認識しているので、vert2 にもコロンの対応がある方が合理的で利便性が高いと個人的には思うのですが、現状の源ノフォントとの互換性が重要という判断ならば、それとも一つの判断かとは思います。

**Comment by trueroad** [comment]
> Adobe-Japan-1 という話をするのなら、そもそも縦書きグリフが登録されるべき CID が全て未定義になっており、それ以前の問題のように見えます。(CID で直接縦書きグリフにアクセスする人は少ないでしょうから、実用上で問題になることはないと思いますが、あってるかどうかをの議論すらできない状態)。

ここについて、何を仰っているのか教えてください。
「縦書きグリフが登録されるべき CID が全て未定義」というのはどういう意味でしょうか？使用頻度の高い縦書きグリフは存在しているはずです。Adobe の CMap の `V` で使用できるグリフはすべて存在していると認識しています。「全て未定義」というのは、どこに何を定義するべきものが未定義になっているということでしょうか？AJ1としてマズいところがあるのであれば、できる限り対応したいと思います（もちろん源ノに存在しないグリフを追加するとかは無理ですが）。

**Comment by trueroad** [comment]
> vert2 は vert のスパーセットであるべきという OpenType の規定を無視してまでこのような実装にしている詳細な理由は不明です。

そのような明確な規定があるのであれば、ぜひ源ノにその旨の Issue を立てていただければと思います。原ノ味だけ修正するより源ノも正くなった方が良いと思いませんか？

**Comment by bogytech** [comment]
そうなんですが、ソースを見る限り知らずに無視したというより何らかの意図をもって無視してる見えます。(個人的にはそれは、多数の国のルールに同時に従うための妥協と推測していますが、違う可能性もあります)。
理由が明確なら変更要求も出せるのですが、他の国での利用状況などは良くわかっていないので本当に変えて大丈夫なのかちょっと言えないのです。Adobe-Japan-1 なら日本語のほとんどフォントがそうなってるので変えるべきと言えるのですけどね。

**Comment by trueroad** [comment]
言語に関わらず「OpenTypeの規定がある」のあれば、それを明示して修正してほしい旨の Issue を立てればよいのではないでしょうか。もし何らかの意図があるのであれば、どのような意図なのか説明を求めればよいと思います。

「Adobe-Japan-1 なら日本語のほとんどフォントがそうなってるので変えるべき」というのは大変申し訳ありませんが、理由として弱いと思っています。AJ1 の規格で規定されている、ということであれば理由として強いのですが。

**Comment by bogytech** [comment]
vrt2 用のグリフが未定義というのは CID の以下の範囲にグリフがないとい話です。
(Adobe-Japan-1 では vrt2 用の回転グリフを以下の範囲に入れることになっています)。
8720-9353
12870-13319
16469-16778
20961-21070
源の明朝の実装を見ると、今回の全角コロンの話とは関係無い余談だったようですが。

**Comment by bogytech** [comment]
> 「Adobe-Japan-1 なら日本語のほとんどフォントがそうなってるので変えるべき」というのは大変申し訳ありませんが、理由として弱いと思っています。AJ1 の規格で規定されている、ということであれば理由として強いのですが。

はい。その判断は尊重します。私の知る限り全角コロンについて規定は無く、あくまでも一般的な実装というレベルだと認識しています。
利便性を考えての提案くらいに受け取ってください。(luatexja のバグとの合わせ技え混乱していたので、分り難い指摘になってしまい、すいません)

**Comment by trueroad** [comment]
> vrt2 用のグリフが未定義というのは CID の以下の範囲にグリフがないとい話です。
> (Adobe-Japan-1 では vrt2 用の回転グリフを以下の範囲に入れることになっています)。
> 8720-9353
> 12870-13319
> 16469-16778
> 20961-21070

これのことですね
https://github.com/adobe-type-tools/Adobe-Japan1#pre-rotated-glyphs
"Pre-Rotated Glyphs" は源ノに存在しないグリフですので、原ノ味にもありません。横書き用のグリフを 90 度回転させることでグリフを作り出すことは可能ではありますが、恐らく単純に回転しただけではダメで調整が必要であろうこと、数が多い割には使用頻度は低いと想定できることから実装していません。

また、
https://blogs.adobe.com/CCJKType/2019/07/aj17-gsub-features.html
では `vrt2` が now-deprecated とされているので、今から整備してもなぁ、というのもあります。

**Comment by bogytech** [comment]
vert2 のグリフがないのは仕方がないもと思います。UAX#50 があれば代替可能というのもその通りかと思います。
ただ、そうすると原の味明朝の vrt2 が飾りになってしまっています。本来の指定するメリットである拡張回転グリフが存在せず、全角コロンの字体が劣るというデメリットだけが存在している状態です。
もし今後も vrt2 のグリフの登録予定がないようなら、いっそのことフォントの機能から vrt2 を削除するのが潔いのではないかと思うのですが、いかがでしょうか？ (ここも源の明朝との互換のためだけに残しておくという判断もあるかとは思いますが)

**Comment by trueroad** [comment]
> vert2 のグリフがないのは仕方がないもと思います。UAX#50 があれば代替可能というのもその通りかと思います。
> ただ、そうすると原の味明朝の vrt2 が飾りになってしまっています。本来の指定するメリットである拡張回転グリフが存在せず、全角コロンの字体が劣るというデメリットだけが存在している状態です。
> もし今後も vrt2 のグリフの登録予定がないようなら、いっそのことフォントの機能から vrt2 を削除するのが潔いのではないかと思うのですが、いかがでしょうか？ (ここも源の明朝との互換のためだけに残しておくという判断もあるかとは思いますが)

仰っている内容は、源ノにも同様に当てはまる話と思います。

原ノ味で絶対に何も対応しないというつもりはありません。しかし、原ノ味がどんな対応をすべきか検討するためには、源ノの実装がなぜ今の状態になっているのか確認する必要があると考えます。そこを抜きにして、 `vrt2` に全角コロンを追加するか、いっそ `vrt2` を全削除するか、あるいはほかの対応をするのか、何もしないのか、議論することはできないと考えています。

**Comment by trueroad** [comment]
源ノ角ゴシックに Issue を立てました
https://github.com/adobe-fonts/source-han-sans/issues/282

**Comment by trueroad** [comment]
源ノの Issue に `vrt2` は "effectively deprecated" だ、という回答がありました。

ここまでは予想通りだったのですが、示していただいた[リンク先](https://forum.glyphsapp.com/t/automatic-feature-code-must-include-vert-in-vrt2/12297/12)の議論で、特に[この書き込み](https://forum.glyphsapp.com/t/automatic-feature-code-must-include-vert-in-vrt2/12297/7)を読むと、かなり込み入った事情があってこうなっていることがわかります。

私の理解の範囲で書きますが、

* `vrt2` が残っているのは、Microsoft appsの縦書きレイアウトが`vrt2`の存在に依存しているから
* `vrt2` がサブセットになっているのは、`vrt2`のLookupテーブルが1つだけでなければならないから
    * 源ノでは `vert` のLookupテーブルは複数あり、そのうちの1つだけを `vrt2` に入れたのでサブセットになってしまった、と思われる

ということだと思っています（少なくとも日本語以外の言語が云々とかいうことではありません）。

原ノ味のGSUB構造は源ノの構造をそのまま変換しているため、この辺はまったく一緒になってしまっています。よって、上記1つ目の理由から `vrt2` を全削除してしまうことはできません。また、2つ目の理由から `vrt2` はサブセットにしておかざるをえません。

もちろん、GSUBの構造を一から完全に作り直して `vrt2` を1つのLookupテーブルにしてサブセットではないようにする、ことは可能だと思います。しかし、最初に出てきた「`vrt2` は "effectively deprecated"」であることや、最新の LuaTeX-ja では現在の（ `vrt2` がサブセットの）原ノ味でも問題ないことから、頑張ってそこまでの労力をかけるべきかというと微妙な感じがしています。

**Comment by bogytech** [comment]
確認、お疲れ様です。

> （少なくとも日本語以外の言語が云々とかいうことではありません）。

ここですが、他言語対応のために、各国共通の部分と、国別に固有の部分を別のテーブルにしているので複数のテーブルに分れているようです。そういう意味で多言語対応が原因だと思います。

> 最新の LuaTeX-ja では現在の（ vrt2 がサブセットの）原ノ味でも問題ないことから、

現時点の最新版の LuaTeX-ja の縦書きでもデフォルトでは vrt2 があれば vert を無視して、vrt2 を優先しまます。そのためコロンの字形が横書きを回転した中心からズレたものになります。
LuaTeX-ja 側を vert 優先に変更してもらう手もあると思いますが、多くの AJ1 フォントでは vrt2 が正しく実装されているので、このフォントのためだけにデフォルトを変えてもらう必要があるか少し悩ましい。

**Comment by trueroad** [comment]
源ノの Issue でOpenType規格を満たしていないということか、と少し食い下がってみていました。その回答がきましたが、どこかの時点でOpenType規格が更新されるべきだろう、という見解で、源ノを修正する気はないようです。

本当にOpenType規格がそのように改訂されたら、源ノも現状の原ノ味も規格的には問題なくなります。
それじゃマズイということであれば、源ノの Issue にその旨をコメントしていただくなどして、参戦していただければと思います。

**Comment by bogytech** [comment]
Source Font は Unicode の文字を全部表示できるようにすることを目標とした Unicode 仕様のフォントなので、Unicode 規格の UAX#50 を原則にする仕方がないのではないかと思っています(一つの見識だと思っています)。
一方で HaranoAji は Unicode 規格のフォントではなく Adobe-Japan-1 規格のフォントなのでそちらに寄せた方が使い勝手が良いのにとも思っています。(そもそも Unicode規格のフォントで良いのなら Source Han 使えば良いだけで、HaranoAji である必要はあんまりない)
将来的に OpenType 規格が変更されたり、Adobe-Japan-1 規格が変更されたりする可能性はあるかもしれませんが、過去との互換性を考えると、そのような変更がすぐにあるとは考え難い。
とはいえ小さな点ですので最終的な判断はおまかせします。個人的には Source Han には Source Han の都合があるので、そこに合わせる必要はないのではという感想です。

**Comment by bogytech** [comment]
「言語ごとに統一されたGSUBテーブル一つにした方が良いのではないでしょうか？そうするとフォントのサイズが大きくなりますが、Souece Han フォントは元が大きいので大した差はありません。」
とだけ書き込んでおきましたが、変更の手数に見合う必要性を感じてはもらえない気がしています。

**Comment by monokano** [comment]
横からすいません。興味深く拝見していました。

源ノ明朝/角ゴシックは当初から、市販のフォントと違って、既存のソフトウェアで幅広く問題なく表示されることを重視していません。むしろ locl 実装の標準フォントとして、ソフトウェア側が源ノ明朝/角ゴシックをちゃんと表示するようにするのが筋だと考えているフシがあります。vrt2 も同様にフォント側ではなくソフトウェア側で vert に移行して対処するのが筋だと考えているのでしょう。

「こっちに合わせろ」という俺様態度のようですが、今までのフォントにはない源ノ明朝/角ゴシックの新しさは、この方針にもあると思います。

ですから、源ノのこの方針に、原ノ味も倣うのかどうか、この選択が重要だと思います。

**Comment by trueroad** [comment]
少々細かいかもしれなくて申し訳ないですが…

> Unicode 仕様のフォント
> Unicode 規格のフォント

源ノは、`cmap` テーブルを使って Unicode コードポイントから CID 番号を得てグリフを特定するので、Unicode に対応したフォントである、ということが言えると思います。このことを指して「Unicode 規格のフォント」「Unicode 規格のフォント」と仰っているのだとすると、これは原ノ味でもまったく同じですので、原ノ味も Unicode に対応したフォントであり、源ノとの違いはありません。

> Adobe-Japan-1 規格のフォント

AJ1規格としては、少なくとも
https://github.com/adobe-type-tools/Adobe-Japan1/blob/master/README-JP.md
を読む限り、OpenType フォントの場合に `vrt2` に使うことのできる CID 番号は定義されていますが、`vert` と `vrt2` の関係がどのようになっていなければならないかなどは定義されていないという認識です。そもそも AJ1 のフォントは OpenType フォントである必要すらない、つまり非 OpenType な AJ1 フォントも存在していて、その場合は GPOS も無いし `vert` も `vrt2` も無い、と認識しています。（もちろんそんなのはかなり古い時代の話で、現代的には OpenType が普通だと思いますが。）

源ノにしろ原ノ味にしろ、現状では `vrt2` が `vert` のサブセットになっているので、OpenType 規格を満たしていません。が、源ノの Issue にあるように OpenType 規格が更新されれば規格的な問題は無くなるものと認識しています。また、ソフトウェア側で源ノの「俺様態度」への対応が進めば、自動的に原ノ味でも対応できたことになると思っています。

一方で、

> 源ノ明朝/角ゴシックは当初から、市販のフォントと違って、既存のソフトウェアで幅広く問題なく表示されることを重視していません。むしろ locl 実装の標準フォントとして、ソフトウェア側が源ノ明朝/角ゴシックをちゃんと表示するようにするのが筋だと考えているフシがあります。

について、確かにそんな感じがします。そもそも、それまであまり採用例が無かった AI0 を選択したこと自体が、この考え方から来ているようにも思います。原ノ味は AI0 ではなくて AJ1 にすることで「俺様態度」を軽減している、ともいえそうな気がします。ですので、

> 源ノのこの方針に、原ノ味も倣うのかどうか、この選択が重要だと思います。

について、完全に源ノに倣うつもりはありません。

また、これまでに、どうして現在の実装になっているのか、修正するのであればどのような GSUB 構造にするべきか、について、かなり知見が集まりました。ですが、残念ながらそれを実現するにはかなりの労力が必要であろうと考えています。TODOリストに入れておくのは、やぶさかではありませんが、そのうちソフトウェア側の対応が進んで、これを修正しないと困る人が誰もいなくなってしまうのではないか、とも思います。

**Comment by bogytech** [comment]
混乱させたかもしれませんが、私の Unicode 仕様のフォントというのは「Unicode 仕様書に規定され文字の処理系を前提にしており、それ以外での利用は考慮していないフォント」くらいの意味です。そしてそういう前提ならば vrt2 は (UAX#50 により) obsolete と言えます。
他の Adobe-Japan-1 フォントを含めて、全てのフォントがそういう前提というわけではありません。もちろん今後は Unicode が中心になっていくので、過去との互換性は切捨てるということならばそれも一つの見識だと思いますが。
OpenType で vrt2 の obsolete にするというのは、全ての文字処理が Unicode 仕様前提になるというのと同等の主張なので、なるとしても先の話ではないでしょうか？
原の味フォントが現在どのような手順で作成されているか承知しておらず、手数がかかり過ぎるということならば無理を言ってすいません。 TODO に入れるだけでも入れておいてもらえればと思います。

**Comment by trueroad** [comment]
> 私の Unicode 仕様のフォントというのは「Unicode 仕様書に規定され文字の処理系を前提にしており、それ以外での利用は考慮していないフォント」
> 他の Adobe-Japan-1 フォントを含めて、全てのフォントがそういう前提というわけではありません。

なにやら見解の相違があるようですね。古いフォントはともかく、現代的なフォントであれば AJ1 であろうがなかろうが Unicode が前提ではないということはあり得ないと認識しております。

> OpenType で vrt2 の obsolete にするというのは、全ての文字処理が Unicode 仕様前提になるというのと同等の主張

彼らも vrt2 は obsolete とまでは言ってませんよね。"effectively deprecated" という言い方をしています。

> 原の味フォントが現在どのような手順で作成されているか承知しておらず

原ノ味フォントの本質は、本リポジトリで配布しているフォントそのものではなくて、[別のリポジトリで配布している生成プログラム](https://github.com/trueroad/HaranoAjiFonts-generator)の方です。この生成プログラムを使えば、どなたでも原ノ味フォントを生成することができますし、プログラムに手を入れれば御所望の仕様になるようにカスタマイズすることもできます。生成プログラムへの pull request も歓迎しております。

本件を修正するなら、思い付きで書いているだけですが

* script 毎、language 毎に、`vert` が参照するLookupテーブルと `vrt2` が参照するLookupテーブルを抽出して、どのLookupテーブルをどのLookupテーブルに統合するかの組み合わせを決定する
* 組み合わせ毎にLookupテーブルの統合処理を行う
    * `vert` にのみ存在するLookupテーブルの中身を、`vert` と `vrt2` 共通に存在するLookupテーブルの中身に追加する
    * `vert` から`vert` にのみ存在するLookupテーブルへの参照を消して、参照されなくなったLookupテーブル本体を消す

みたいなことをすればよいと思っています。

**Comment by bogytech** [comment]
見解が少し違いそうですね。そこは本筋ではないので置いておいて、
おっしゃるような感じの修正ができると問題無さそうですね。
もし時間がかかるようなら、ドキュメントで vert の使用を推奨するとか、リンクしてある fontspec ファイルとかにも Vertical=Alternates を追加するなどしておくのが親切かもしれません。
こちらで修正案を作成して提案(pull req)したいところですが、個人的に色々立て込んでいて時間が取れず要領の悪い要望するだけになってしまってすいません。

**Comment by bogytech** [comment]
ちなみ個人的に考えていたのは Source Han から抽出するのではなくて CMAP の -H と -V から独自の縦書きへのグリフのマッピングを作成して、それに基いて OpenType の GSUB を定義するような方法でした。(特に検証したわけでもない思いつきみたいなもので不十分かもしれません)。

**Comment by trueroad** [comment]
[20210102 版](https://github.com/trueroad/HaranoAjiFonts/releases/tag/20210102)をリリースしています。
ご確認ください。

**Comment by bogytech** [comment]
VRT2 におけるコロンの字形が望ましもの(VERTと同じもの)になっていることを確認しました。
いち早い対応、ありがとうございます。

**Comment by trueroad** [comment]
クローズします
