### ISSUE TITLE
pwid が間違っている？

### ISSUE THREAD

**Issue by h20y6m** [trueroad/HaranoAjiFonts#7]
リリースされたばかりの 20210101 ですが GSUB の pwid (Lookup 12) に CID+15518 ⇒ CID+15986 のような横組み用グリフから縦組み用グリフへの変換が含まれているように見えます。

さらに vert, vrt2 (Lookup 20) にはこれらの変換が含まれてなさそうです。

> プロポーショナルかな縦組み用は LuaTeX でも XeTeX でも うまく扱うことができなかったため、動作確認ができていません。

に関係しているかもしれません。

**Comment by trueroad** [comment]
ご指摘ありがとうございます。
vert へ追加すべき置き換えを誤って pwid に追加してしまっていたようです。

とりあえず
https://github.com/trueroad/HaranoAjiFonts-generator/commit/0ae20bbe5cb47ea641666102e427c85b907a24cf
の修正をしてビルドしたフォントでは LuaTeX や XeTeX でプロポーショナル縦組みグリフが選択できるようになりました。

近日中に修正版をリリースしたいと思います。

なお、今回 pwid へ誤って追加してしまった置き換えは、すべて「プロポーショナル横組み用グリフ」から「プロポーショナル縦組み用グリフ」への置き換えなので、pwid を二重に適用するとか、pkna と pwid を両方適用するとかしない限りは発動しないものと思います。普通は二重に適用することはないでしょうし、pkna と pwid は OpenType 規格的には排他なので両方適用されることはないと思っています。ですので 20210101 版でも大抵は問題なくお使いいただけると思います。

**Comment by h20y6m** [comment]
ちょうど XeTeX（というよりは xdvipdfmx）でプロポーショナル（非全角）な縦組みグリフの出力がずれるのを調べていて、そこにプロポーショナル縦組み用仮名が追加された原ノ味がリリースされたので試してみたら……という感じです。（Slack に書いたやつです）

急ぐわけはありませんので、修正版がリリースされてからまた確認します。

**Comment by trueroad** [comment]
[20210102 版](https://github.com/trueroad/HaranoAjiFonts/releases/tag/20210102)で修正しました。
ご確認ください。

LuaTeX や XeTeX で動作確認できるようになりました。おかげ様で、グリフの位置計算が間違っていたのも発見できたので修正してあります。

XeTeX は最新版 (XeTeX 3.14159265-2.6-0.999992 + xdvipdfmx 20201216) だとかえってうまくいかなくて、2020年春頃の XeTeX (XeTeX 3.14159265-2.6-0.999992 + xdvipdfmx 20200315) ならうまくいくようです。

**Comment by h20y6m** [comment]
ありがとうございます。
修正を確認しました。
