### ISSUE TITLE
CMap H かつ jis.tfm で字送りが合わない

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFonts#8]
いつもお世話になります。
下記のソースで `ptex999.tex` の場合に横方向の字送りが合いません。
縦方向もわずかに大きすぎるような気がします。
IPAフォントでは想定通りの結果になるのでpLaTeXのソースや dvi, tfm, CMap の問題ではないように思います。
upLaTeX + HaranoAji に替えると想定通りになります。
jis.tfm のメトリックと HaranoAji の相性のようなものだろうかと疑っています。
ご検討いただければ幸いです。

```
% platex ptex999.tex
\documentclass{jsarticle}
\usepackage[T1]{fontenc}

\AtBeginDvi{\special{pdf:mapline jis H HaranoAjiMincho-Regular.otf}}
%\AtBeginDvi{\special{pdf:mapline jis H ipamp.ttf}}

\begin{document}
あいうえお、天地玄黄。ABC xyz. HaranoAji
\end{document}
```
```
% platex ptex998.tex
\documentclass{jsarticle}
\usepackage[T1]{fontenc}

%\AtBeginDvi{\special{pdf:mapline jis H HaranoAjiMincho-Regular.otf}}
\AtBeginDvi{\special{pdf:mapline jis H ipamp.ttf}}

\begin{document}
あいうえお、天地玄黄。ABC xyz. IPA
\end{document}
```
```
% uplatex uptex995.tex
\documentclass[uplatex]{jsarticle}
\usepackage[T1]{fontenc}

\AtBeginDvi{\special{pdf:mapline uprml-h unicode HaranoAjiMincho-Regular.otf}}

\begin{document}
あいうえお、天地玄黄。ABC xyz. upLaTeX
\end{document}

```
![image](https://user-images.githubusercontent.com/3814120/160240852-872fa36d-9822-4c58-9398-876d54fe47b9.png)

**Comment by aminophen** [comment]
いろいろな勘違いの組み合わせ，という感じがします。原ノ味フォントは正しいはずです。

* jis.tfm は pTeX 用 JFM（約物は半角で GLUEKERN 設定あり）であって DVI ドライバ用 JFM（約物も全角）ではないのでマップファイルに指定するのは誤りだと思います。一方で uprml-h.tfm は DVI ドライバ用 JFM です。
*  また ipamp.ttf はプロポーショナルフォントなので，普通の JFM と合わせて使うのは仕様外だと思います（等幅なのは ipam.ttf）。なんとなく正しい字送りに見えるのは偶然にすぎず，dvipdfmx では幅ズレが蓄積するという挙動によるズレがメトリックの齟齬とたまたま近いだけではないでしょうか。

**Comment by t-tk** [comment]
@aminophen さん、コメントありがとうございます。
こちらでもう少し検討します。

**Comment by t-tk** [comment]
お騒がせしました。ご指摘の通り `jis` → `rml`, `ipamp.ttf` → `ipam.ttf` に直したら正しくなりました。
ありがとうございました。

```
\documentclass{jsarticle}
\usepackage[T1]{fontenc}

\AtBeginDvi{\special{pdf:mapline rml H HaranoAjiMincho-Regular.otf}}
%\AtBeginDvi{\special{pdf:mapline rml H ipamp.ttf}}

\begin{document}
\fbox{\hbox{あいうえお、天地玄黄。ABC xyz. HaranoAji}}
\end{document}
```

![image](https://user-images.githubusercontent.com/3814120/160243343-a4431c8b-c541-4857-bad4-da71baeefcfd.png)

**Comment by trueroad** [comment]
すでに解決しているようですが、私が原ノ味の動作確認に使う方法を書いておきます。
本来であれば小塚と比較して同じ結果が得られれば OK とすればよいと思っていますが、小塚はもっていませんし、Acrobat Reader 付属の小塚を TeX で埋め込むとライセンス違反になるらしいので、代わりにフォント非埋め込みで PDF を作ります。今回のであればこんな感じでしょうか。 jis.tfm を間違い承知でそのまま指定しています。

```ptex999-noembed.tex
% platex ptex999-noembed.tex
\documentclass{jsarticle}
\usepackage[T1]{fontenc}

\AtBeginDvi{\special{pdf:mapline jis H !Ryumin-Light}}

\begin{document}
あいうえお、天地玄黄。ABC xyz. NoEmbed
\end{document}
```

これで作った PDF を Acrobat Reader で表示させると小塚で代替表示してくれますしライセンス違反にはならないと思います。ただし小塚を埋め込んだ時とは微妙に違うのかもしれませんがとりあえず代用にはなると思います。
これを原ノ味を埋め込んだ PDF と比較してみると、グリフのデザインが違うだけで位置はまったく同じになりました。小塚を埋め込んだときも同じ結果になるのでしょうから原ノ味の問題ではなかろう、ということがわかります。（繰り返しになりますが本来は小塚を埋め込んだものと比較すべきなので代用程度ではあります）

**Comment by t-tk** [comment]
@trueroad さん、ありがとうございます。今後は教えていただいた手順でまず確認します。
