### ISSUE TITLE
新Adobe-Japan1-7, U+31350

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFonts#9]
最近出た Adobe-Japan1-7 January 18, 2023 Release に関して
https://github.com/adobe-type-tools/cmap-resources/releases/tag/20230118

以下のようなmappingが追加されたそうです。
U+1B132 HIRAGANA LETTER SMALL KO → CID+12269 (Vertical CMap, CID+12270)
U+1B155 KATAKANA LETTER SMALL KO → CID+12271 (Vertical CMap, CID+12272)
U+31350 (Extension H) → CID+19130

このうち、小書き「こ」「コ」は源ノにグリフが無いとのことでしたので仕方ありません。
CID19130 (U+2EAC, U+31350)は、グリフがあるようです。
新規の U+31350 は、おそらく現状でHaranoAjiではU+2EACとCIDの対応があるが、U+31350の対応が未設定なのかな、と思います。
この文字コードを使う人は稀と思いますが、ご参考になれば幸いです。

**Comment by trueroad** [comment]
お知らせいただきありがとうございます。
次期リリースでは対応できるようにしたいと思います。

**Comment by trueroad** [comment]
[20230223 版](https://github.com/trueroad/HaranoAjiFonts/releases/tag/20230223)にて対応しました。
ご確認ください。

**Comment by t-tk** [comment]
早速のご対応に感謝します。
U+31350 が Unicode指定でバッチリ出ました。素晴らしい。
いつもありがとうございます。
